const n=[];let t,o;function u(){return !!t}function r(n){const o=t,u=()=>{};t=u,a(u);const r=n(()=>{S(u),t=void 0;});return t=o,r}function c(n){const o=t;t=void 0;const u=n();return t=o,u}function e(t){let u=o;o=[];const r=t();let c=o;return o=u,c.forEach(t=>{if(t.t!==n){const o=t.t;t.t=n,t(o);}}),r}function i(u){function r(c){if(0===arguments.length)return t&&!r.__o.has(t)&&(r.__o.add(t),t.o.push(r)),u;if(o)return r.t===n&&o.push(r),r.t=c,c;u=c;const e=t;return t=void 0,r.u=new Set(r.__o),r.u.forEach(n=>n.i=!1),r.u.forEach(n=>{n.i||n();}),t=e,u}return r.$o=!0,r.__o=new Set,r.t=n,r}function f(n,o){function u(){const r=t;t&&t.__c.push(u);const c=u.__c;return S(u),u.i=!0,t=u,o=n(o),c.forEach(n=>{-1===u.__c.indexOf(n)&&(n.i=!0);}),function n(t){return t.reduce((t,o)=>t.concat(o,n(o.__c)),[])}(u.__c).forEach(s),t=r,o}function r(){return u.i?u.o.forEach(n=>n()):o=u(),o}return n.s=u,a(u),u(),r.$o=!0,r}function s(n){n.i&&n.o.forEach(t=>{t.u&&t.u.delete(n);});}function d(n){return t&&t.l.push(n),n}function l(n){return f(n),()=>S(n.s)}function v(n){S(n.s);}function S(n){n.__c.forEach(S),n.o.forEach(t=>{t.__o.delete(n),t.u&&t.u.delete(n);}),n.l.forEach(n=>n()),a(n);}function a(n){n.o=[],n.__c=[],n.l=[];}

var n$1 = /*#__PURE__*/Object.freeze({
	__proto__: null,
	S: f,
	cleanup: d,
	computed: f,
	isListening: u,
	o: i,
	observable: i,
	root: r,
	sample: c,
	subscribe: l,
	transaction: e,
	unsubscribe: v
});

const t$1=(n,e,o,f)=>{let i={};for(let s=1;s<e.length;s++){const r=e[s],u="number"==typeof r?o[r]:r,l=e[++s];if(1===l)f[0]=u;else if(3===l)f[1]=Object.assign(f[1]||{},u);else if(5===l)(f[1]=f[1]||{})[e[++s]]=u;else if(6===l){let t=e[++s],n=(f[1]=f[1]||{})[t],o=i[t];o||"function"!=typeof u&&"function"!=typeof n||(o=n&&[n]||[],f[1][t]=function(){let t="";for(var n=0;n<o.length;n++)t+="function"==typeof o[n]?o[n]():o[n];return t}),o?o.push(u):f[1][t]+=u+"";}else if(l){const e=()=>n.apply(null,t$1(n,u,o,["",null]));f.push("function"==typeof f[0]?e:e());}else f.push(u);}return f},n$2=function(t){let n,e,o=1,f="",i="",s=[0];const r=t=>{1===o&&(t||(f=f.replace(/^\s*\n\s*|\s*\n\s*$/g,"")))?s.push(t||f,0):3===o&&(t||f)?(s.push(t||f,1),o=2):2===o&&"..."===f&&t?s.push(t,3):2===o&&f&&!t?s.push(!0,5,f):o>=5&&((f||!t&&5===o)&&(s.push(f,o,e),o=6),t&&(s.push(t,o,e),o=6)),f="";};for(let u=0;u<t.length;u++){u&&(1===o&&r(),r(u));for(let l=0;l<t[u].length;l++)n=t[u][l],1===o?"<"===n?(r(),s=[s],o=3):f+=n:4===o?"--"===f&&">"===n?(o=1,f=""):f=n+f[0]:i?n===i?i="":f+=n:'"'===n||"'"===n?i=n:">"===n?(r(),o=1):o&&("="===n?(o=5,e=f,f=""):"/"===n&&(o<5||">"===t[u][l+1])?(r(),3===o&&(s=s[0]),o=s,(s=s[0]).push(o,2),o=0):" "===n||"\t"===n||"\n"===n||"\r"===n?(r(),o=2):f+=n),3===o&&"!--"===f&&(o=4,s=s[0]);}return r(),s},e$1=new Map,o$1=function(o){let f=e$1.get(this);return f||(f=new Map,e$1.set(this,f)),f=t$1(this,f.get(o)||(f.set(o,f=n$2(o)),f),arguments,[]),f.length>1?f:f[0]},f$1=function(){const t=o$1.apply(this,arguments);if(t)return Array.isArray(t)?this(t):"object"==typeof t?t:this([t])};function e$2(){const t=f$1.bind(this);return (this.wrap||t).apply(t,arguments)}

const o$2={},f$2=[];let i$1=0;function r$1(n,t,e){let r;return "string"==typeof t?t=document.createTextNode(t):t instanceof Node||(t=o$2.h(f$2,t)),11===t.nodeType&&(r=t.firstChild)&&r!==t.lastChild&&(r.t=t.lastChild.t=++i$1),n.insertBefore(t,e||null),void 0===r?t:r}function s$1(n){return this.o[n.type](n)}function u$1(n,t){for(let t in n)o$2[t]=n[t];return function(){const n=f$2.slice.call(arguments);let e;function i(f){if(null==f);else if("string"==typeof f)e?r$1(e,f):e=t?document.createElementNS("http://www.w3.org/2000/svg",f):document.createElement(f);else if(Array.isArray(f))e||(e=document.createDocumentFragment()),f.forEach(i);else if(f instanceof Node)e?r$1(e,f):e=f;else if("object"==typeof f)o$2.property(e,f,null,t);else if("function"==typeof f)if(e){const n=r$1(e,"");o$2.insert(e,f,n);}else e=f.apply(null,n.splice(1));else r$1(e,""+f);}return n.forEach(i),e}}o$2.insert=function(n,t,e,f,i){return n=e&&e.parentNode||n,i=i||f instanceof Node&&f,t===f||(f&&"string"!=typeof f||!("string"==typeof t||"number"==typeof t&&(t+=""))?"function"==typeof t?o$2.subscribe((function(){f=o$2.insert(n,t.call({el:n,endMark:e}),e,f,i);})):(function(n,t,e,o){if(e){if(t){if(!o){const t=(o=e.previousSibling||n.lastChild).t;if(t)for(o=o.previousSibling;o&&o.t!==t;)o=o.previousSibling;}let t;for(;o&&o!==e;)t=o.nextSibling,n===o.parentNode&&(n.removeChild(o),o.t=0),o=t;}}else n.textContent="";}(n,f,e,i),f=null,t&&!0!==t&&(f=r$1(n,t,e))):(null!=f&&n.firstChild?e?(e.previousSibling||n.lastChild).data=t:n.firstChild.data=t:e?r$1(n,t,e):n.textContent=t,f=t)),f},o$2.property=function(n,t,e,f,i){if(null!=t)if(!e||"attrs"===e&&(f=!0))for(e in t)o$2.property(n,t[e],e,f,i);else"o"!==e[0]||"n"!==e[1]||t.$o?"function"==typeof t?o$2.subscribe((function(){o$2.property(n,t.call({el:n,name:e}),e,f,i);})):i?n.style.setProperty(e,t):f||"data-"===e.slice(0,5)||"aria-"===e.slice(0,5)?n.setAttribute(e,t):"style"===e?"string"==typeof t?n.style.cssText=t:o$2.property(n,t,null,f,!0):("class"===e&&(e+="Name"),n[e]=t):function(n,t,e){t=t.slice(2).toLowerCase();const f=o$2.cleanup(()=>n.removeEventListener(t,s$1));e?n.addEventListener(t,s$1):f(),(n.o||(n.o={}))[t]=e;}(n,e,t);},o$2.add=r$1,o$2.h=u$1(n$1),o$2.hs=u$1(n$1,!0);const l$1=i;function c$1(){return o$2.h.apply(o$2.h,arguments)}function a$1(){return o$2.hs.apply(o$2.hs,arguments)}function p(){return e$2.apply(c$1,arguments)}function m(){return e$2.apply(a$1,arguments)}

export { o$2 as api, u$1 as context, c$1 as h, a$1 as hs, p as html, l$1 as o, l$1 as observable, m as svg };
